apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-admin
spec:
  type: {{ .Values.services.type }}

  ports:
  - name: kong-admin
    port: {{ .Values.services.admin.servicePort }}
    targetPort: {{ .Values.services.admin.containerPort }}
    protocol: TCP
  - name: kong-admin-ssl
    port: {{ .Values.services.admin.serviceSSLPort }}
    targetPort: {{ .Values.services.admin.containerSSLPort }}
    protocol: TCP
  selector:
    app: {{ .Release.Name }}-{{ .Values.kongAppName }}
