# Default values for kong.
# Declare variables to be passed into your templates.

kongAppName: kong-gateway
kongInstanceCount: 1
provisionDB: true
kong:
  admin:
    servicePort: 8001
    serviceSSLPort: 8444
    containerPort: 8001
    containerSSLPort: 8444
    type: NodePort #Options: NodePort, ClusterIP, LoadBalancer
  proxy:
    servicePort: 8000
    serviceSSLPort: 8443
    containerPort: 8000
    containerSSLPort: 8443
    type: NodePort #Options: NodePort, ClusterIP, LoadBalancer
  logLevel: debug #Options: debug, info, notice, warn, error, crit, alert, emerg
  database:
    useCassandra: false
    name: kong-database
    postgres:
      username: kong
      databse: kong
      password: kong
      host: postgres
      port: 5432
    cassandra:
      contactPoints: cassandra
      port: 9042
      keyspace: kong
      replcation: 2
resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  #requests:
  #  cpu: 100m
  #  memory: 128Mi
