# Default values for kong.
# Declare variables to be passed into your templates.

kongAppName: kong-gateway
kongInstanceCount: 1

services:
  admin:
    servicePort: 8001
    serviceSSLPort: 8444
    containerPort: 8001
    containerSSLPort: 8444
  proxy:
    servicePort: 8000
    serviceSSLPort: 8443
    containerPort: 8000
    containerSSLPort: 8443

database:
  # STRONGLY RECOMMENDED
  # Deploy using existing backend
  # Use helm to install and configure either PostreSQL or Cassandra
  # Update the configuration to point to the store
  # https://github.com/kubernetes/charts/tree/master/stable/postgresql or https://github.com/kubernetes/charts/tree/master/incubator/cassandra

  # deployment:
  #   deployStore: false
  # KONG_DATABASE: postgres
  # KONG_PG_USER: kong
  # KONG_PG_PASSWORD: kong
  # KONG_PG_DATABASE: kongdb
  # KONG_PG_HOST: postgres_service_name.example_namespace.svc.cluster.local

  # WARNING - The solution below doesn't use persistent volumes so data is lost on pod/cluster restart.
  # Deploy with postgres backend:
  deployment:
    deployStore: true
    databaseName: postgres
  KONG_DATABASE: postgres
  KONG_PG_USER: kong
  KONG_PG_PASSWORD: kong
  KONG_PG_DATABASE: kong
  KONG_PG_HOST: postgres
  KONG_LOG_LEVEL: debug #Options: debug, info, notice, warn, error, crit, alert, emerg
  KONG_PG_PORT: 5432


  # WARNING - volumes don't use persistent volumes so data is lost on pod/cluster restart.
  # Deploy with cassandra backend:
  # deployment:
  #     deployStore: true
  #     databaseName: cassandra
  # KONG_DATABASE: cassandra
  # KONG_CASSANDRA_CONTACT_POINTS: kong-cassandra
  # KONG_CASSANDRA_PORT: 9042
  # KONG_CASSANDRA_KEYSPACE: kong
  # KONG_CASSANDRA_REPL_FACTOR: "2"


resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  #requests:
  #  cpu: 100m
  #  memory: 128Mi
